<a href="https://colab.research.google.com/github/Rangerix/MicroArrayDatasets/blob/master/threading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import threading
import numpy
import time

In [3]:
print("hello")

hello


In [0]:
def parf(i,j):
  #print("i=",i," j=",j)
  mat[i][j]=arr[i]+arr[j]

In [0]:
n=3
mat=numpy.full((n,n),-2.0)
arr=[2,4,6]

In [16]:
for i in range(3):
  for j in range(3):
    parf(i,j)
print(mat)

i= 0  j= 0
i= 0  j= 1
i= 0  j= 2
i= 1  j= 0
i= 1  j= 1
i= 1  j= 2
i= 2  j= 0
i= 2  j= 1
i= 2  j= 2
[[ 4.  6.  8.]
 [ 6.  8. 10.]
 [ 8. 10. 12.]]


In [24]:
threads=[]
for i in range(3):
  for j in range(3):
    mythread=threading.Thread(target=parf,args=[i,j])
    mythread.start()
    threads.append(mythread)
for t in threads:
  t.join()
print(mat)
print("here am I")

[[ 4.  6.  8.]
 [ 6.  8. 10.]
 [ 8. 10. 12.]]
here am I
